# Generated by Django 6.0 on 2025-12-15 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
                ('birthdate', models.DateField(verbose_name='Birth Date')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('qr_code_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64, verbose_name='Role Name')),
                ('description', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(max_length=128, verbose_name='Invoice Number')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('GCASH', 'G-Cash'), ('QR_PAYMENT', 'QR Payment')], default='CASH', max_length=15, verbose_name='Payment Method')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Payment Amount')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_member_invoices', to='memberships.member')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField(verbose_name='Billing Date')),
                ('start_date', models.DateField(verbose_name='Biling Start Date')),
                ('end_date', models.DateField(verbose_name='Biling End Date')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_invoice_billings', to='memberships.invoice')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_member_billings', to='memberships.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ManyToManyField(to='memberships.role'),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ManyToManyField(to='memberships.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
